# Generated by Django 2.2.7 on 2019-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('contractor', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('energy_meter', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=30)),
                ('tc_relationship', models.CharField(max_length=5)),
                ('tp_relationship', models.CharField(max_length=5)),
            ],
        ),
    ]
